import { useState } from "react";
import { Bell, ChevronDown, User, BarChart3, Layers, Coins, Star } from "lucide-react";
import Logo from "./Logo.jsx";
import SearchBar from "./SearchBar.jsx";
import MarketTicker from "./MarketTicker.jsx";
import { LiveStatusDot, MarketStatusBadge } from "./MarketShared.jsx";
import { COLORS, fontBody } from "../utils/market";

const NAV_PAGES = [{ key: "stocks", label: "Stocks", icon: BarChart3 }, { key: "fno", label: "F&O", icon: Layers }, { key: "commodities", label: "Commodities", icon: Coins }, { key: "watchlist", label: "Watchlist", icon: Star }];
function NotificationsButton() { const [open, setOpen] = useState(false); return <div style={{ position: "relative" }}><button onClick={() => setOpen((value) => !value)} aria-label="Notifications" style={{ background: "none", border: "none", cursor: "pointer", padding: 6, display: "flex" }}><Bell size={18} color="rgba(255,255,255,0.65)" /></button>{open && <div style={{ position: "absolute", top: "calc(100% + 8px)", right: 0, width: 240, background: "#fff", border: `1px solid ${COLORS.line}`, borderRadius: 10, padding: 14, zIndex: 70 }}><strong style={{ fontFamily: "'Sora', system-ui", color: COLORS.ink }}>Notifications</strong><div style={{ fontFamily: fontBody, fontSize: 12, color: COLORS.inkMuted, marginTop: 6 }}>No alerts yet. Price alerts and research-call notifications will appear here once your backend is connected.</div></div>}</div>; }
function ProfileMenu({ onLogout }) { const [open, setOpen] = useState(false); return <div style={{ position: "relative" }}><button onClick={() => setOpen((value) => !value)} title="Account" style={{ display: "flex", alignItems: "center", gap: 4, background: "none", border: "none", cursor: "pointer" }}><div style={{ width: 34, height: 34, borderRadius: "50%", background: COLORS.accent, display: "flex", alignItems: "center", justifyContent: "center" }}><User size={16} color="#fff" /></div><ChevronDown size={13} color="rgba(255,255,255,0.6)" className="lv-hide-mobile" /></button>{open && <div onClick={onLogout} style={{ position: "absolute", top: "calc(100% + 8px)", right: 0, width: 180, background: "#fff", borderRadius: 10, padding: 14, zIndex: 70, color: COLORS.down, fontFamily: fontBody, fontSize: 13 }}>Log out</div>}</div>; }
export default function Header({ loggedIn, view, indices, commodities, onSelectInstrument, feedStatus, onLogin, onSignup, onLogout, onNavigate }) { return <div>{!loggedIn && <div style={{ background: COLORS.accent, padding: "7px 16px", textAlign: "center", fontFamily: fontBody, fontWeight: 600, fontSize: 12.5, color: "#fff" }}>🚀 Stocro is in early access — launching soon. Open your account to get in first.</div>}<div style={{ background: COLORS.navy }}><div className="lv-navbar"><div onClick={() => onNavigate("landing")}><Logo /></div><SearchBar onSelect={onSelectInstrument} dark /><div className="lv-nav-links">{!loggedIn ? <><button onClick={onLogin} style={{ fontFamily: fontBody, fontSize: 13.5, color: "#fff", background: "transparent", border: "1px solid rgba(255,255,255,0.35)", borderRadius: 8, padding: "8px 16px", cursor: "pointer" }}>Log in</button><button onClick={onSignup} style={{ fontFamily: fontBody, fontSize: 13.5, color: "#fff", background: COLORS.accent, border: "none", borderRadius: 8, padding: "9px 16px", cursor: "pointer" }}>Sign up</button></> : <><NotificationsButton /><ProfileMenu onLogout={onLogout} /></>}</div></div><div className="lv-nav-pages">{NAV_PAGES.map(({ key, label, icon: Icon }) => <span key={key} onClick={() => onNavigate(key)} className="lv-nav-page-item" style={{ color: view === key ? "#fff" : "rgba(255,255,255,0.65)", fontWeight: view === key ? 600 : 400, borderBottom: view === key ? `2px solid ${COLORS.accent}` : "2px solid transparent" }}><Icon size={14} />{label}</span>)}</div></div><MarketTicker indices={indices} commodities={commodities} /><div style={{ background: COLORS.navy, display: "flex", justifyContent: "center", gap: 14, padding: "5px 0" }}><LiveStatusDot status={feedStatus} /><span style={{ color: "rgba(255,255,255,0.2)" }}>·</span><MarketStatusBadge compact /></div></div>; }
