import { useState } from "react";
import { Bell, ChevronDown, Home, Search, User } from "lucide-react";
import Logo from "./Logo.jsx";
import SearchBar from "./SearchBar.jsx";

const pages = [{ key: "stocks", label: "Stock Discovery" }, { key: "fno", label: "Index F&O" }, { key: "commodities", label: "Commodities" }, { key: "watchlist", label: "Watchlist" }];
function Quote({ item }) { return <div className="top-quote"><strong>{item?.symbol || "Index"}</strong><span className={item?.price >= item?.open ? "positive" : "negative"}>{Number.isFinite(item?.price) ? `₹${item.price.toLocaleString("en-IN", { maximumFractionDigits: 2 })}` : "Market Closed"}</span><small className={item?.price >= item?.open ? "positive" : "negative"}>{Number.isFinite(item?.price) && Number.isFinite(item?.open) ? `${((item.price - item.open) / item.open * 100).toFixed(2)}%` : "Showing Last Session Data"}</small></div>; }
export default function Header({ loggedIn, view, indices = [], commodities = [], onSelectInstrument, onLogin, onSignup, onLogout, onNavigate }) {
	const [open, setOpen] = useState(false);
	return <header><div className="terminal-topbar"><button className="brand-button" onClick={() => onNavigate("landing")}><Logo /></button><div className="top-quotes"><Quote item={indices[0]} /><Quote item={indices[1]} /></div><SearchBar onSelect={onSelectInstrument} dark /><nav className="desktop-nav"><button onClick={() => onNavigate("landing")} title="Home"><Home size={14} /></button><button className={view !== "landing" ? "active" : ""} onClick={() => onNavigate("stocks")}>Markets</button><button onClick={() => onNavigate("dashboard")}>Portfolio</button><button onClick={() => onNavigate("watchlist")}>Watchlist</button></nav><div className="account-actions">{loggedIn ? <><button title="Notifications"><Bell size={15} /></button><button title="Account" onClick={() => setOpen(!open)}><User size={15} /><ChevronDown size={12} /></button>{open && <button className="logout-popover" onClick={onLogout}>Log out</button>}</> : <><button className="terminal-btn" onClick={onLogin}>Log in</button><button className="terminal-btn terminal-btn-primary" onClick={onSignup}>Sign up</button></>}</div></div><div className="terminal-nav">{pages.map((page) => <button key={page.key} className={view === page.key ? "active" : ""} onClick={() => onNavigate(page.key)}>{page.label}</button>)}</div></header>;
}
