import { useEffect, useRef, useState } from "react";
import { Search } from "lucide-react";
import api from "../services/api";
import { COLORS, fontBody } from "../utils/market";

export default function SearchBar({ onSelect, dark }) {
  const [query, setQuery] = useState(""); const [matches, setMatches] = useState([]); const [open, setOpen] = useState(false); const boxRef = useRef(null);
  useEffect(() => { const close = (event) => { if (!boxRef.current?.contains(event.target)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  useEffect(() => { const value = query.trim(); if (value.length < 2) { setMatches([]); return undefined; } const controller = new AbortController(); const timer = setTimeout(() => api.get(`/market/search?q=${encodeURIComponent(value)}`, { signal: controller.signal }).then(({ data }) => setMatches(Array.isArray(data.data) ? data.data.slice(0, 8) : [])).catch(() => setMatches([])), 250); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const pick = (match) => { onSelect(match); setQuery(""); setMatches([]); setOpen(false); };
  return <div className="search-shell" ref={boxRef} style={{ position: "relative", flex: "1 1 180px", minWidth: 120, maxWidth: 380 }}><div style={{ display: "flex", alignItems: "center", gap: 8, padding: "7px 10px", border: `1px solid ${dark ? "#303535" : COLORS.line}`, borderRadius: 6, background: dark ? "#171a1a" : "#fff" }}><Search size={14} color="#899191" /><input value={query} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onFocus={() => setOpen(true)} placeholder="Search for anything" style={{ width: "100%", border: 0, outline: 0, background: "transparent", color: dark ? "#eef3f8" : COLORS.ink, fontFamily: fontBody, fontSize: 12 }} /></div>{open && matches.length > 0 && <div style={{ position: "absolute", top: "calc(100% + 5px)", left: 0, right: 0, zIndex: 40, overflow: "hidden", border: "1px solid #303535", borderRadius: 7, background: "#1b1e1e", boxShadow: "0 14px 30px #0008" }}>{matches.map((match) => <button key={`${match.exchange}:${match.symbol}`} onClick={() => pick(match)} style={{ display: "flex", justifyContent: "space-between", width: "100%", padding: "10px 12px", border: 0, borderBottom: "1px solid #303535", background: "transparent", textAlign: "left", color: "#eef3f8" }}><span><strong>{match.symbol}</strong><small style={{ display: "block", color: "#899191", marginTop: 2 }}>{match.name || match.kind}</small></span><small style={{ color: "#6d83ff" }}>{match.exchange}</small></button>)}</div>}</div>;
}
