import { useEffect, useRef, useState } from "react";
import { Search, Sparkles } from "lucide-react";
import api from "../services/api";
import { COLORS, fontBody } from "../utils/market";
import ResearchCallPanel from "./ResearchCallPanel.jsx";

export default function SearchBar({ onSelect, dark }) {
  const [query, setQuery] = useState(""); const [matches, setMatches] = useState([]); const [open, setOpen] = useState(false); const [aiOpen, setAiOpen] = useState(false); const boxRef = useRef(null);
  useEffect(() => { const close = (event) => { if (boxRef.current && !boxRef.current.contains(event.target)) { setOpen(false); setAiOpen(false); } }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  useEffect(() => { const q = query.trim(); if (q.length < 2) { setMatches([]); return undefined; } const controller = new AbortController(); const timer = setTimeout(() => { api.get(`/market/search?q=${encodeURIComponent(q)}`, { signal: controller.signal }).then(({ data }) => setMatches(Array.isArray(data.data) ? data.data.slice(0, 8) : [])).catch((error) => { if (error.name !== "CanceledError" && error.code !== "ERR_CANCELED") setMatches([]); }); }, 350); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const pick = (match) => { onSelect(match); setQuery(""); setOpen(false); setAiOpen(false); };
  return <div ref={boxRef} style={{ position: "relative", flex: "1 1 160px", minWidth: 90, maxWidth: 360 }}><div style={{ display: "flex", alignItems: "center", gap: 6, background: dark ? "rgba(255,255,255,0.09)" : "#fff", border: dark ? "1px solid rgba(255,255,255,0.14)" : `1px solid ${COLORS.line}`, borderRadius: 8, padding: "7px 10px" }}><Search size={14} color={dark ? "rgba(255,255,255,0.5)" : COLORS.inkMuted} /><input value={query} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onFocus={() => setOpen(true)} placeholder="Search or ask AI…" style={{ border: "none", outline: "none", background: "transparent", fontFamily: fontBody, fontSize: 12.5, flex: 1, minWidth: 0, color: dark ? "#fff" : COLORS.ink }} /><button onClick={() => setAiOpen((value) => !value)} title="AI research" aria-label="AI research" style={{ background: "none", border: "none", cursor: "pointer", display: "flex", padding: 2, color: aiOpen ? COLORS.accent : dark ? "rgba(255,255,255,0.5)" : COLORS.inkMuted }}><Sparkles size={14} /></button></div>{open && matches.length > 0 && <div style={{ position: "absolute", top: "calc(100% + 6px)", left: 0, right: 0, background: "#fff", border: `1px solid ${COLORS.line}`, borderRadius: 10, boxShadow: "0 12px 32px rgba(8,27,58,0.22)", zIndex: 70 }}>{matches.map((match) => <div key={`${match.exchange}:${match.symbol}`} onClick={() => pick(match)} style={{ display: "flex", justifyContent: "space-between", padding: "10px 12px", cursor: "pointer", borderTop: `1px solid ${COLORS.line}` }}><div><div style={{ fontFamily: fontBody, fontSize: 13, color: COLORS.ink }}>{match.symbol}</div><div style={{ fontFamily: fontBody, fontSize: 11, color: COLORS.inkMuted }}>{match.name || match.kind}</div></div><div style={{ fontFamily: fontBody, fontSize: 11, color: COLORS.inkMuted }}>{match.exchange}</div></div>)}</div>}{aiOpen && <div style={{ position: "absolute", top: "calc(100% + 6px)", left: 0, right: 0, zIndex: 70, minWidth: 260 }}>{matches[0] ? <ResearchCallPanel instrument={matches[0]} /> : <div style={{ background: "#fff", border: `1px solid ${COLORS.line}`, borderRadius: 10, padding: 14, fontFamily: fontBody, fontSize: 12.5, color: COLORS.inkMuted }}>Type a stock, index, or commodity above for an AI research call.</div>}</div>}</div>;
}
