import { useEffect, useState } from "react";
import TradingViewChart from "../components/TradingViewChart.jsx";
import { marketApi } from "../services/market";
import { COLORS, fontBody, fontDisplay } from "../utils/market";
export default function Fno({ index }) {
  const [data, setData] = useState(null); const [error, setError] = useState(false);
  useEffect(() => { let active = true; const request = index?.symbol ? marketApi.fno(index.symbol) : marketApi.fnoOverview(); request.then((response) => active && setData(response.data.data)).catch(() => active && setError(true)); return () => { active = false; }; }, [index?.symbol]);
  const quote = data?.quote; const instrument = data?.instrument; const symbol = instrument?.tradingsymbol || instrument?.symbol || index?.symbol;
  return <div style={{ background: COLORS.paper }}><div className="lv-page-wrap"><h1 style={{ fontFamily: fontDisplay, fontWeight: 600, fontSize: 26, color: COLORS.ink, margin: "0 0 6px" }}>F&O</h1><p style={{ fontFamily: fontBody, fontSize: 13.5, color: COLORS.inkMuted, margin: "0 0 20px" }}>Futures and options data from Angel One SmartAPI.</p>{error && <div style={{ color: COLORS.down, fontFamily: fontBody, marginBottom: 16 }}>Live F&O data is unavailable.</div>}{symbol && <div style={{ background: COLORS.paperCard, border: `1px solid ${COLORS.line}`, borderRadius: 14, padding: 14 }}><TradingViewChart symbol={symbol} height={360} /></div>}{quote && <div style={{ background: COLORS.paperCard, border: `1px solid ${COLORS.line}`, borderRadius: 14, marginTop: 18, padding: 18, fontFamily: fontBody }}><h2 style={{ fontFamily: fontDisplay, color: COLORS.ink }}>Contract details</h2><div className="lv-summary-grid">{[["Expiry", data.expiry], ["Strike", data.strike], ["Open interest", data.openInterest], ["Volume", quote.volume], ["Last price", quote.ltp]].map(([label, value]) => <div key={label}><div style={{ color: COLORS.inkMuted, fontSize: 12 }}>{label}</div><strong style={{ color: COLORS.ink }}>{value ?? "-"}</strong></div>)}</div></div>}{!quote && !error && <div style={{ color: COLORS.inkMuted, fontFamily: fontBody, padding: 24 }}>Select a valid F&O contract to view live data.</div>}</div></div>;
}
