import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { authApi } from "./services/api";
import { useGlobalStyles, useLiveFeed, useMarket } from "./hooks/marketHooks";
import { COMMODITY_INSTRUMENTS, COLORS, INDEX_INSTRUMENTS, LIVE_FEED_SOCKET_URL, STOCK_INSTRUMENTS, fontBody, mergeLive } from "./utils/market";
import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";
import AboutPage from "./pages/About.jsx";
import Landing from "./pages/Landing.jsx";
import Login from "./pages/Login.jsx";
import Dashboard from "./pages/Dashboard.jsx";
import Stocks from "./pages/Stocks.jsx";
import Commodities from "./pages/Commodities.jsx";
import Watchlist from "./pages/Watchlist.jsx";
import Fno from "./pages/Fno.jsx";
import StockDetails from "./pages/StockDetails.jsx";
import AllIndices from "./pages/AllIndices.jsx";

const GLOBAL_CSS = `.lv-reset * { box-sizing: border-box; } .lv-reset { width: 100%; } .lv-hide-mobile { display: initial; } .lv-hide-desktop { display: none; } .lv-app { display: flex; flex-direction: column; min-height: 100%; } .lv-main { flex: 1; } .lv-hero { display: flex; gap: 56px; align-items: flex-start; padding: 72px 32px 96px; } .lv-hero-copy { flex: 1 1 480px; max-width: 560px; } .lv-hero-card { flex: 1 1 380px; max-width: 400px; } .lv-feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 20px; } .lv-nav-links { display: flex; align-items: center; gap: 12px; } .lv-summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 14px; } .lv-main-cols { display: flex; gap: 18px; align-items: flex-start; } .lv-col { flex: 1 1 380px; min-width: 0; } .lv-movers-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; } .lv-navbar { padding: 14px 24px; display: flex; align-items: center; justify-content: space-between; gap: 14px; } .lv-nav-pages { display: flex; gap: 4px; padding: 0 20px; overflow-x: auto; scrollbar-width: none; border-top: 1px solid rgba(255,255,255,0.08); } .lv-nav-pages::-webkit-scrollbar { display: none; } .lv-nav-page-item { display: inline-flex; align-items: center; gap: 6px; font-family: 'IBM Plex Sans', system-ui, sans-serif; font-size: 13.5px; padding: 10px 14px; cursor: pointer; white-space: nowrap; flex-shrink: 0; } .lv-footer-grid { display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 32px; } .lv-chip-row { display: flex; gap: 8px; flex-wrap: wrap; } .lv-page-wrap { max-width: 1120px; margin: 0 auto; padding: 32px 20px 64px; } @media (max-width: 1080px) { .lv-hero { flex-direction: column; padding: 48px 20px 64px; gap: 32px; } .lv-hero-card { max-width: 100%; } .lv-main-cols { flex-direction: column; } .lv-footer-grid { grid-template-columns: 1fr 1fr; } } @media (max-width: 760px) { .lv-hide-mobile { display: none; } .lv-hide-desktop { display: initial; } .lv-navbar { padding: 10px 14px; gap: 8px; flex-wrap: wrap; } .lv-nav-pages { padding: 0 10px; } .lv-nav-page-item { font-size: 12.5px; padding: 9px 10px; } .lv-footer-grid { grid-template-columns: 1fr; gap: 22px; } }`;

export default function AppCoordinator() {
  useGlobalStyles(GLOBAL_CSS);
  const location = useLocation(); const navigate = useNavigate();
  const [view, setView] = useState("landing"); const [authMode, setAuthMode] = useState("login"); const [session, setSession] = useState(null); const [searchTarget, setSearchTarget] = useState(null);
  useEffect(() => { const stockMatch = location.pathname.match(/^\/stocks\/([^/]+)$/); const fnoMatch = location.pathname.match(/^\/fno\/([^/]+)$/); if (stockMatch) { setSearchTarget(decodeURIComponent(stockMatch[1])); setView("stock-detail"); } else if (fnoMatch) { setSearchTarget(decodeURIComponent(fnoMatch[1])); setView("fno"); } else if (location.pathname === "/login") setView("login"); else if (location.pathname === "/dashboard") setView("dashboard"); else if (location.pathname === "/watchlist") setView("watchlist"); else if (location.pathname === "/stocks") setView("stocks"); else if (location.pathname === "/fno") setView("fno"); else if (location.pathname === "/stocks-fno") setView("stocks-fno"); else if (location.pathname === "/commodities") setView("commodities"); else if (location.pathname === "/all-indices") setView("all-indices"); else if (location.pathname === "/news") setView("news"); }, [location.pathname]);
  useEffect(() => { const token = localStorage.getItem("stoclio_token"); if (!token) return; authApi.me().then(({ data }) => { setSession(data); setView("dashboard"); }).catch(() => { localStorage.removeItem("stoclio_token"); setSession(null); }); }, []);
  const simIndices = useMarket(INDEX_INSTRUMENTS, "NSE"); const simCommodities = useMarket(COMMODITY_INSTRUMENTS, "MCX"); const simStocks = useMarket(STOCK_INSTRUMENTS, "NSE"); const { ticks, status } = useLiveFeed(LIVE_FEED_SOCKET_URL);
  const indices = useMemo(() => mergeLive(simIndices, ticks), [simIndices, ticks]); const commodities = useMemo(() => mergeLive(simCommodities, ticks), [simCommodities, ticks]); const stocks = useMemo(() => mergeLive(simStocks, ticks), [simStocks, ticks]); const loggedIn = Boolean(session);
  const goLogin = () => { setAuthMode("login"); navigate("/login"); }; const goSignup = () => { setAuthMode("signup"); navigate("/login"); }; const logout = async () => { try { await authApi.logout(); } catch {} localStorage.removeItem("stoclio_token"); setSession(null); navigate("/"); }; const navigateTo = (target) => { if (target === "watchlist" && !loggedIn) return goLogin(); setView(target); navigate(target === "landing" ? "/" : `/${target}`); }; const selectInstrument = (instrument) => { setSearchTarget(instrument.symbol); if (instrument.kind === "commodity") navigateTo("commodities"); else if (instrument.kind === "index") navigateTo("fno"); else navigate(`/stocks/${encodeURIComponent(instrument.symbol)}`); };
  return <div style={{ fontFamily: fontBody, width: "100%", minHeight: 640, background: COLORS.paper }} className="lv-app"><Header loggedIn={loggedIn} view={view} indices={indices} commodities={commodities} onSelectInstrument={selectInstrument} feedStatus={status} onLogin={goLogin} onSignup={goSignup} onLogout={logout} onNavigate={navigateTo} /><div className="lv-main">{view === "landing" && <Landing stocks={stocks} onSignup={goSignup} />}{view === "login" && <Login mode={authMode} onAuthenticated={(user) => { setSession(user); navigate("/dashboard"); }} onBack={() => navigate("/")} />}{view === "dashboard" && loggedIn && <Dashboard indices={indices} commodities={commodities} stocks={stocks} />}{view === "about" && <AboutPage />}{view === "stocks" && <Stocks stocks={stocks} />}{view === "stock-detail" && <StockDetails symbol={searchTarget} />}{view === "commodities" && <Commodities commodities={commodities} initialSymbol={searchTarget} />}{view === "watchlist" && loggedIn && <Watchlist stocks={stocks} initialSymbol={searchTarget} />}{view === "fno" && <Fno initialSymbol={searchTarget} />}{view === "stocks-fno" && <Fno initialSymbol="RELIANCE" />}{view === "all-indices" && <AllIndices indices={indices} />}{view === "news" && <AllIndices indices={indices} news />}</div><Footer onNavigate={navigateTo} /></div>;
}
